project:
  type: default
  output-dir: build

execute:
  freeze: auto

format:
  typst:
    toc: false
    toc-depth: 2
    columns: 1
    papersize: us-letter
    margin:
      x: 0.92in
      y: 0.72in
    mainfont: "Libertinus Serif"
    mathfont: "New Computer Modern Math"
    codefont: "Menlo"
    fontsize: 10.2pt
    number-sections: true
    section-numbering: "1.1"
    fig-cap-location: bottom
    tbl-cap-location: top
    link-citations: true
    link-bibliography: true
    bibliographystyle: annual-reviews-author-date
    biblio-title: References
    include-in-header:
      - style.typ
    keep-typ: true

bibliography: references.bib
link-citations: true
crossref:
  fig-title: "Fig."
  tbl-title: "Table"
  fig-prefix: "Fig."
  tbl-prefix: "Table"
